### ISSUE TITLE
Properly designed error output

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ignition#69]
When Ghost encounters an error, we have quite a lot of info that we output. Right now, it's not output in a particularly well designed way.

An error has the following fields:
- *message* (describes the error)
- *type* (error type e.g. internal error)
- *code* (a unique code e.g. UPLOAD_FAILED)
- *help* (what to do? docs?)
- *context* (context of a request e.g. path of a file which was uploaded)
- *error details* (similar to context, basically used for sub error information e.g. theme upload errors)
- *level* (normal or critical, how important is an error)
- *stack* (stack trace on the server side)

The most useful are:

- message: **what** happened / the basic generated error message, often very technical
- context: any info we have about **why** or **how** this happened
- help: a suggestion, command, or url which should help figure out **how to fix it**

Then: 
- type & code  are useful meta data

Finally:

- If you’re actively working _on_ Ghost the stack trace is helpful.
- If you’re a developer working on something else (theme, API integration) error details are probably more relevant.

**Comment by peterzimon** [comment]
⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️

# IGNORE THIS DESIGN


⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️

## Design

<img width="1352" alt="ghost-cli-error-formatting" src="https://user-images.githubusercontent.com/353959/52225664-34b05200-28ab-11e9-9d80-1d47ce2cf0a2.png">

### Details
Structure:

```[...]ERROR

[red](type)
[red](message)

[white bold](context)
[blue](help)

<if (details) != null>
[white bold]Details:
      [lightgrey](detail)
</if>

[white bold]Error code:
      [lightgrey](errorcode)

---------------------------------

[lightgrey](stack)
```

Level seems to be not a useful info (noise) for developers so we simply don't show it. Error code can be used to refer to an error on forum, support etc.

**Comment by kirrg001** [comment]
**Update**: We will just focus on following the existing design.

The _existing_ design is:

- Red: What's wrong?
- White: Why?
- Yellow: How do I fix it?

We still follow the existing design:

- message, type, error details = red (what)
- context = white (why)
- help = yellow (how to fix)

We "just" need to tweak our pretty streamer, because:

- we print level, which we should not
- we suffer from #66 
- we have added prefixes

**Comment by vikaspotluri123** [comment]
Here's a case where [as a dev] it's difficult to parse the error details because it's JSON:

```
[2019-02-14 17:53:23] ERROR

NAME: ThemeValidationError
MESSAGE: The currently active theme "casper" is invalid.

level: normal

ERROR DETAILS:
    "[\n\t{\n\t\t\"fatal\": true,\n\t\t\"level\": \"error\",\n\t\t\"rule\": \"Templates must contain valid Handlebars\",\n\t\t\"details\": \"Oops! You seemed to have used invalid Handlebars syntax. This mostly happens, when you use a helper that is not supported.<br>\\n        See the full list of available helpers <a href=\\\"https://themes.ghost.org/docs/helpers\\\" target=_blank>here</a>.\",\n\t\t\"failures\": [\n\t\t\t{\n\t\t\t\t\"ref\": \"homepage.hbs\",\n\t\t\t\t\"message\": \"post doesn't match page - 13:3\"\n\t\t\t}\n\t\t],\n\t\t\"code\": \"GS005-TPL-ERR\"\n\t}\n]"

ThemeValidationError: The currently active theme "casper" is invalid.
    at ThemeValidationError.GhostError (/home/vikas/gtmp/versions/2.14.3/core/server/lib/common/errors.js:10:26)
    at new ThemeValidationError (/home/vikas/gtmp/versions/2.14.3/core/server/lib/common/errors.js:52:20)
    at validationFailure (/home/vikas/gtmp/versions/2.14.3/core/server/services/themes/index.js:50:50)
    at tryCatcher (/home/vikas/gtmp/versions/2.14.3/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/vikas/gtmp/versions/2.14.3/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/vikas/gtmp/versions/2.14.3/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/vikas/gtmp/versions/2.14.3/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/vikas/gtmp/versions/2.14.3/node_modules/bluebird/js/release/promise.js:690:18)
    at _drainQueueStep (/home/vikas/gtmp/versions/2.14.3/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/home/vikas/gtmp/versions/2.14.3/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/home/vikas/gtmp/versions/2.14.3/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/vikas/gtmp/versions/2.14.3/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
```
