### ISSUE TITLE
Problem when args are of different values

### ISSUE THREAD

**Issue by pysysops** [TryGhost/Ignition#73]
The logger crashes if it receives an array of arguments of different types like:
```
['A string message', Error: Unexpected close
      at ..... ]
```

The error thrown is:
```
/Users/tbirkett/GhostProjects/Zuul/node_modules/ghost-ignition/lib/logging/GhostLogger.js:284
                modifiedArguments.err = value;
                                      ^

TypeError: Cannot create property 'err' on string 'AMQP connection error. '
    at /Users/tbirkett/GhostProjects/Zuul/node_modules/ghost-ignition/lib/logging/GhostLogger.js:284:39
    at arrayEach (/Users/tbirkett/GhostProjects/Zuul/node_modules/ghost-ignition/node_modules/lodash/_arrayEach.js:15:9)
    at forEach (/Users/tbirkett/GhostProjects/Zuul/node_modules/ghost-ignition/node_modules/lodash/forEach.js:38:10)
    at ZuulLogger.log (/Users/tbirkett/GhostProjects/Zuul/node_modules/ghost-ignition/lib/logging/GhostLogger.js:279:9)
    at ZuulLogger.error (/Users/tbirkett/GhostProjects/Zuul/node_modules/ghost-ignition/lib/logging/GhostLogger.js:351:14)
    at ChannelModel.connection.on (/Users/tbirkett/GhostProjects/Zuul/node_modules/moleculer/src/transporters/amqp.js:147:20)
    at ChannelModel.emit (events.js:189:13)
    at ChannelModel.EventEmitter.emit (domain.js:441:20)
    at Connection.emit (events.js:189:13)
    at Connection.EventEmitter.emit (domain.js:441:20)
    at Connection.C.onSocketError (/Users/tbirkett/GhostProjects/Zuul/node_modules/amqplib/lib/connection.js:352:10)
    at Socket.emit (events.js:194:15)
    at Socket.EventEmitter.emit (domain.js:441:20)
    at endReadableNT (_stream_readable.js:1103:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
error Command failed with exit code 1.
```

I believe this is due to the `log(type, args)` function.

**Comment by pysysops** [comment]
Fixing in custom logger which extends GhostLogger
